Add capi cluster backup and restore role
stackhpc/ansible-collection-azimuth-ops pull request #192
Opened 2023-10-19 15:09 UTC by sd109

2023-11-27 15:32 UTC, mkjpryor requested changes

2023-11-28 13:58 UTC, sd109 commented on roles/velero/tasks/install.yml
> +    kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl apply -f -
It doesn't look like it. The controllers [readme](https://github.com/kubernetes-csi/external-snapshotter#usage) states

> it is strongly recommended that Kubernetes distributors bundle and deploy the controller and CRDs as part of their Kubernetes cluster management process

but doesn't say how it expects us to do that. I guess we could package it in capi-helm-charts but that's probably just side-stepping the problem.

2023-11-28 14:06 UTC, sd109 commented on roles/velero/tasks/restore.yml
> +    kubectl -n $NAMESPACE rollout status statefulset/consul-server --watch
Good catch, but yes sadly `rollout restart` isn't enough. I'll adapt the script to work with a variable number of consul servers.

2023-11-28 14:51 UTC, mkjpryor commented on roles/velero/tasks/install.yml
> +    kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl apply -f -
That actually feels a lot more like what we want to do...

2023-11-28 14:53 UTC, mkjpryor commented on roles/velero/tasks/restore.yml
> +    kubectl -n $NAMESPACE rollout status statefulset/consul-server --watch
The sooner we drop Consul the better...

2023-11-28 15:01 UTC, sd109 commented on roles/velero/tasks/install.yml
> +    kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl apply -f -
Long term yes, I agree. Probably not a quick bit of work though. Would we just convert the yaml resources that are being applied here into `Manifest` addons? Or would you want to do it some other way? (e.g. package it as a Helm chart)

2023-11-28 15:09 UTC, sd109 commented on roles/velero/tasks/install.yml
> +    kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl apply -f -
Actually there is this https://gitlab.cern.ch/kubernetes/automation/charts/snapshot-controller/-/tree/master/snapshot-controller

2023-11-28 15:50 UTC, mkjpryor commented on roles/velero/tasks/install.yml
> +    kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl apply -f -
Also this, which actually ships a chart into a repo we can use

https://github.com/piraeusdatastore/helm-charts/tree/main/charts/snapshot-controller

Actually, that datastore also looks kind of interesting...

2023-11-29 09:38 UTC, sd109 commented on roles/velero/tasks/install.yml
> +    kubectl -n kube-system kustomize deploy/kubernetes/snapshot-controller | kubectl apply -f -
Switched to this piraeus chart for now

2023-12-01 17:03 UTC, merged