Bump slurm to v1.144 with RL8 and RL9 images
stackhpc/ansible-collection-azimuth-ops pull request #452
Opened 2024-03-28 10:36 UTC by sjpb

2024-03-28 13:24 UTC, mkjpryor requested changes

2024-03-28 13:24 UTC, mkjpryor commented on roles/community_images/defaults/main.yml
>      container_format: bare
How does anyone get to use the other image?

2024-03-28 13:25 UTC, sjpb commented on roles/community_images/defaults/main.yml
>      container_format: bare
Arcus config will use v2, see PR there.

2024-03-29 17:30 UTC, mkjpryor commented on roles/community_images/defaults/main.yml
>      container_format: bare
Can we just add the v2 image to `community_images_extra` in the Arcus config then?

2024-04-03 09:25 UTC, mkjpryor approved these changes
LGTM. rstudio test failure is not related.

2024-04-03 09:26 UTC, merged